pipeline:
  build:
    image: python
    commands: 
    - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - python get-pip.py
    - pip install selenium
    - sudo mv geckodriver /usr/local/bin
    - sudo mv chromedriver /usr/local/bin
    - export PATH=$PATH:/usr/local/bin/geckodriver
    - export PATH=$PATH:/usr/local/bin/chromedriver
    -
services:
  selenium:
    image: selenium/hub

  chrome:
    image: selenium/node-chrome
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium
      HUB_PORT_4444_TCP_PORT: 4444
      DISPLAY: ":99.0"

  firefox:
    image: selenium/node-firefox
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium
      HUB_PORT_4444_TCP_PORT: 4444
      DISPLAY: ":98.0"